language: cpp

before_install:
    - sudo apt-get -y install cmake libboost-dev libboost-test-dev

dist: bionic
sudo: required

compiler:
    - clang
    - gcc

env:
    - CONFIG=Debug
    - CONFIG=Release
    - CONFIG=ReleaseDebug HYBRID=1
    - CONFIG=DebugRelease HYBRID=1

notifications:
 email:
   on_success: change
   on_failure: always

script: dev/travis
