language: cpp

before_install:
    - sudo apt-get -y install cmake

dist: bionic
sudo: required

compiler:
    - clang
    - gcc

env:
    - CONFIG=Debug
    - CONFIG=Release
    - CONFIG=ReleaseDebug
    - CONFIG=DebugRelease
    - CONFIG=Debug PREINSTALL_BOOST=true
    - CONFIG=Release PREINSTALL_BOOST=true
    - CONFIG=ReleaseDebug PREINSTALL_BOOST=true
    - CONFIG=DebugRelease PREINSTALL_BOOST=true

notifications:
 email:
   on_success: change
   on_failure: always

script: dev/travis
